### PR TITLE
Create CollectingBlock

### PR DESCRIPTION
**Pull request by alberto512**

### CODE REVIEW

**Comment by pollend** [comment]
The block does not quite work. You still need to tweak this a bit more before I merge this in. A lot of empty null items appear in the secondary inventory. You will need to test this beforehand as well.

image

**Comment by alberto512** [comment]
I don't see any error like the one of the picture that you sent. I test it with only additionalrails and core enabled and with this cart: https://gist.github.com/alberto512/f128b2289793aa95a2b3436734bb2393

**Comment by pollend** [comment]
I was testing it with the hoover cart

**Comment by Cervator** [comment]
I can confirm the issue with the hoovercart - results in a bunch of `?`s in the inventory. Same thing with the track layer cart. Maybe something differs between them and the sample one in the Gist

I tried putting that into a prefab but while the game registered it I couldn't retrieve it as an item. Are you doing anything beyond just having that prefab available @alberto512 ? Is there another way of placing the sample cart or do you have a `-Item` prefab as well? That's the case for the hoover and harvester

**Pull request closed without merging**
